public class denemesamet{
    
public integer hesap(integer a,integer b){

integer sum = a + b;
return sum;
}
public integer carp(integer x,integer y){

    integer sum1 = x * y;
    return sum1;


}
public integer bolme(integer z,integer t){

    integer sum2 = z / t;
    return sum2;
}

public string firstName;
public string lastName;
public integer age;
public boolean spor;
private string schoolName = 'Bu kisi 57. mektepte okumaktadir';

public void message(){

system.debug('bu kisi benim gardasim ula!!!!');

}

}



