public class ListCollection {
 
 // bu metot parametre olarak bir isim listesi alsin. Bu isimleri tek tek yazsin..

public static void printNames(List<String> adList){

     // Listemizi iki sekilde bos olup olmadigini kontrol edebiliriz.dolu ise islem yapariz bossa yapmayiz//
        if (adList.size()>0){
            integer counter = 1;
       for (string eachName: AdList){
           system.debug('fir dongusu ' + counter + '. defa dondu');
           system.debug(eachName);
           counter++;
        }
    }
        if(!adList.isempty()){

        }   

    }
 }

