DatetimeMethodsDemo d1 = new DatetimeMethodsDemo();
d1.birthdateInMilliSeconds();
d1.printOfferEndDateTime();
d1.printSubscriptionEndDate();
d1.calculateAgeInDays();
d1.calculateAgeInMonths();

Decimal decvalue = 27.01;
System.debug('Decimal: ' + decvalue);
Long longValue = 2147483648L;
system.debug('Long: ' + longValue);
Object Mihra = 'This is my daughter';
Object Age = 1;
system.debug( Mihra + Age );